export const FETCHING_CART = 'FETCHING_CART'
export const FETCHING_CART_SUCCESS = 'FETCHING_CART_SUCCESS'
export const FETCHING_CART_ERROR = 'FETCHING_CART_ERROR'

export const ADD_CART = 'ADD_CART'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_ERROR = 'ADD_CART_ERROR'

export const DELETE_CART = 'DELETE_CART'
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_ERROR = 'DELETE_CART_ERROR'