export const FETCHING_PRODUCT = "FETCHING_PRODUCT"
export const FETCHING_PRODUCT_SUCCESS = "FETCHING_PRODUCT_SUCCESS"
export const FETCHING_PRODUCT_ERROR = "FETCHING_PRODUCT_ERROR"

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT'
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS'
export const ADD_NEW_PRODUCT_ERROR = 'ADD_NEW_PRODUCT_ERROR'