export const FETCHING_USER = "FETCHING_USER"
export const FETCHING_USER_SUCCESS = "FETCHING_USER_SUCCESS"
export const FETCHING_USER_ERROR = "FETCHING_USER_ERROR"


export const ADD_NEW_USER = 'ADD_NEW_USER'
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS'
export const ADD_NEW_USER_ERROR = 'ADD_NEW_USER_ERROR'